services:
  postgres:
    image: postgres:16-alpine
    container_name: producer66_db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: producer66
      POSTGRES_PASSWORD: producer66
      POSTGRES_DB: producer66
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
