#!/bin/bash

clear

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🔍 DIAGNÓSTICO RÁPIDO - ¿Por qué no veo logs?"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Verificar si hay servidor corriendo
echo "⏳ Verificando si el servidor está corriendo..."
sleep 1

if lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null 2>&1; then
    PID=$(lsof -Pi :3000 -sTCP:LISTEN -t)
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "✅ SERVIDOR CORRIENDO (PID: $PID)"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "El servidor de Next.js está corriendo en puerto 3000."
    echo ""
    echo "📍 Los logs del webhook deben aparecer en la terminal"
    echo "   donde ejecutaste 'npm run dev'"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🧪 PROBANDO EL ENDPOINT..."
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Enviando petición de prueba al webhook..."
    echo "(Esto debería generar logs en la terminal del servidor)"
    echo ""
    sleep 1
    
    # Hacer petición de prueba
    response=$(curl -s -w "\n%{http_code}" -X POST http://localhost:3000/api/webhooks/clerk \
      -H "Content-Type: application/json" \
      -d '{"test": true}' 2>&1)
    
    http_code=$(echo "$response" | tail -n1)
    
    echo "Respuesta del servidor: HTTP $http_code"
    echo ""
    
    if [ "$http_code" == "400" ] || [ "$http_code" == "200" ]; then
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "✅ ¡EL ENDPOINT FUNCIONA!"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "El webhook se ejecutó correctamente."
        echo ""
        echo "🔍 AHORA MIRA LA TERMINAL DONDE EJECUTASTE 'npm run dev'"
        echo ""
        echo "Deberías ver líneas como estas:"
        echo "  🚀 WEBHOOK CLERK - INICIO DE EJECUCIÓN"
        echo "  📋 Headers recibidos:"
        echo "  ..."
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "📋 SI VES LOS LOGS:"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "✅ El código funciona perfectamente"
        echo "✅ El problema es que Clerk no está enviando eventos"
        echo ""
        echo "👉 Siguiente paso: Configurar el webhook en Clerk"
        echo "   Lee: DIAGNOSTICO_RESUMEN.md"
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "📋 SI NO VES LOS LOGS:"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "⚠️  Puede que estés viendo la terminal incorrecta"
        echo ""
        echo "Los logs aparecen SOLO en la terminal donde ejecutaste"
        echo "'npm run dev', no en esta terminal."
        echo ""
        echo "Busca la terminal que tiene este mensaje:"
        echo "  ✓ Ready on http://localhost:3000"
        echo ""
        echo "Esa es donde aparecen los logs del webhook."
        echo ""
    elif [ "$http_code" == "404" ]; then
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "❌ ERROR 404 - ENDPOINT NO ENCONTRADO"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "Next.js no encuentra la ruta del webhook."
        echo ""
        echo "🔧 SOLUCIÓN:"
        echo ""
        echo "1. Detén el servidor (busca la terminal con npm run dev"
        echo "   y presiona Ctrl+C)"
        echo ""
        echo "2. Ejecuta:"
        echo "   rm -rf .next"
        echo "   npm run dev"
        echo ""
        echo "3. Vuelve a ejecutar este script"
        echo ""
    else
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "⚠️  RESPUESTA INESPERADA: $http_code"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "Hay un problema con el endpoint."
        echo ""
        echo "Revisa la terminal donde corre 'npm run dev'"
        echo "para ver los errores completos."
        echo ""
    fi
    
else
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "❌ NO HAY SERVIDOR CORRIENDO"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Esta es la razón por la que NO ves los console.log:"
    echo ""
    echo "  ❌ Next.js no está corriendo"
    echo "  ❌ El código del webhook no se ejecuta"
    echo "  ❌ Los logs no pueden aparecer"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🔧 SOLUCIÓN:"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "1. Abre una nueva terminal"
    echo ""
    echo "2. Ejecuta estos comandos:"
    echo ""
    echo "   cd $(pwd)"
    echo "   npm run dev"
    echo ""
    echo "3. Espera a ver este mensaje:"
    echo "   ✓ Ready on http://localhost:3000"
    echo ""
    echo "4. DEJA ESA TERMINAL ABIERTA"
    echo "   (Los logs del webhook aparecerán AHÍ)"
    echo ""
    echo "5. Vuelve a ejecutar este script en OTRA terminal:"
    echo "   ./quick-check.sh"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
fi

echo ""
echo "📖 Para más información, lee: POR_QUE_NO_VEO_LOGS.md"
echo ""
