-- Copia y pega esto en el SQL Editor de Supabase (https://supabase.com/dashboard/project/xwrjiepxkgyqalsordws/sql)

-- 1. Crear la tabla clients
CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  email TEXT UNIQUE NOT NULL,
  registration_type TEXT NOT NULL,
  password TEXT, -- Nullable para usuarios de Google/Clerk
  "firstName" TEXT, 
  "secondName" TEXT,
  "clerkId" TEXT UNIQUE,
  "imageUrl" TEXT,
  username TEXT
);

-- 2. Crear la tabla beats
CREATE TABLE IF NOT EXISTS beats (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  title TEXT NOT NULL,
  bpm INTEGER NOT NULL,
  key TEXT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  tag TEXT NOT NULL,
  "audioUrl" TEXT
);

-- 3. Habilitar Row Level Security (RLS)
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE beats ENABLE ROW LEVEL SECURITY;

-- 4. Crear políticas de seguridad (Policies)

-- Clients: Lectura pública (o restringida)
CREATE POLICY "Enable read access for all users" ON clients FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON clients FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for users based on email" ON clients FOR UPDATE USING (true);

-- Beats: Lectura pública
CREATE POLICY "Enable read access for all users" ON beats FOR SELECT USING (true);
-- Beats: Insertar solo admins (por ahora abierto para pruebas, AJUSTAR EN PRODUCCIÓN)
CREATE POLICY "Enable insert for all users" ON beats FOR INSERT WITH CHECK (true);

-- 5. Índices
CREATE INDEX IF NOT EXISTS clients_email_idx ON clients (email);
CREATE INDEX IF NOT EXISTS clients_clerk_id_idx ON clients ("clerkId");
