-- VERSIÓN CORREGIDA (Snake Case Standard)
-- Ejecuta esto en Supabase SQL Editor

-- 1. Si ya existe la tabla, la eliminamos para recrearla limpia
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS beats CASCADE;

-- 2. Crear la tabla clients (Snake Case)
CREATE TABLE clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  email TEXT UNIQUE NOT NULL,
  registration_type TEXT NOT NULL,
  password TEXT,
  first_name TEXT,  -- snake_case
  second_name TEXT, -- snake_case
  clerk_id TEXT UNIQUE, -- snake_case
  image_url TEXT, -- snake_case
  username TEXT
);

-- 3. Crear la tabla beats
CREATE TABLE beats (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  title TEXT NOT NULL,
  bpm INTEGER NOT NULL,
  key TEXT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  tag TEXT NOT NULL,
  audio_url TEXT -- snake_case
);

-- 4. Habilitar RLS
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE beats ENABLE ROW LEVEL SECURITY;

-- 5. Políticas
CREATE POLICY "Enable read access for all users" ON clients FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON clients FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for users based on email" ON clients FOR UPDATE USING (true);

CREATE POLICY "Enable read access for all users" ON beats FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON beats FOR INSERT WITH CHECK (true);

-- 6. Índices
CREATE INDEX clients_email_idx ON clients (email);
CREATE INDEX clients_clerk_id_idx ON clients (clerk_id);
