-- Esquema exacto basado en la imagen de la tabla 'clients'
-- Copia y pégalo en el Editor SQL de Supabase si necesitas recrear la tabla.

CREATE TABLE IF NOT EXISTS public.clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  email TEXT UNIQUE,       -- El icono de huella indica restricción UNIQUE
  registration_type TEXT,
  password TEXT,
  "firstName" TEXT,        -- Comillas requeridas para soportar camelCase en PostgreSQL
  "secondName" TEXT        -- Comillas requeridas para soportar camelCase en PostgreSQL
);

-- Habilitar seguridad (Row Level Security) es buena práctica
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;

-- Políticas básicas (adaptar según seguridad requerida)
CREATE POLICY "Public profiles are viewable by everyone" 
ON public.clients FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile" 
ON public.clients FOR INSERT WITH CHECK (true);
